version: '2'
# Assumes docker for mac.
#
# - There is no docker0 bridge network in docker for mac: https://docs.docker.com/docker-for-mac/networking/
#   so alias names for the containers are commented out.
#
services:
    web:
        container_name: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_web-1"
        hostname: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_web-1"
        image: "devopscenter/000000.web:${dcSTACK_VERSION}"
        ports:
            - "80:80"
            - "8000:8000"
            - "443:443"
        links:
            - "pgmaster-1"
            - "worker"
            - "redismaster"
        volumes:
            - "${dcAPP}:/data/deploy/current"
            - "/wheelhouse"
            - "${dcDATA}:/dataload"
            - "${dcUTILS}:/utils"
            - "${APP_UTILS_CONFIG}:/app-utils/conf"
            - "${APP_UTILS_KEYS}:/app-utils/keys"
        working_dir: "/data/deploy/current"
        env_file:
            - "${GENERATED_ENV_FILE}"
        volumes_from:
            - syslog

    worker:
        container_name: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_worker-1"
        hostname: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_worker-1"
        image: "devopscenter/000000.worker:${dcSTACK_VERSION}"
        ports:
            - "5555:5555"
        links:
            - "pgmaster-1"
            - "redismaster"
        volumes:
            - "${dcAPP}:/data/deploy/current"
            - /wheelhouse
            - "${dcUTILS}:/utils"
            - "${APP_UTILS_CONFIG}:/app-utils/conf"
            - "${APP_UTILS_KEYS}:/app-utils/keys"
        working_dir: "/data/deploy/current"
        env_file:
            - "${GENERATED_ENV_FILE}"
        volumes_from:
            - syslog

    pgmaster-1:
        container_name: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_pgmaster-1"
        hostname: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_pgmaster-1"
        image: "devopscenter/db_postgres:${dcSTACK_VERSION}"
        ports:
            - "5432:5432"
        env_file:
            - "${GENERATED_ENV_FILE}"
        volumes:
            - pg-db:/media/data/postgres/
            - "${dcUTILS}:/utils"
            - "${APP_UTILS_CONFIG}:/app-utils/conf"
            - "${APP_UTILS_KEYS}:/app-utils/keys"
        working_dir: "/data/deploy/current"
        volumes_from:
            - syslog


    redismaster:
        container_name: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_redismaster"
        hostname: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_redismaster"
        image: "devopscenter/db_redis:${dcSTACK_VERSION}"
        env_file:
            - "${GENERATED_ENV_FILE}"
        ports:
            - "6379:6379"
        volumes:
            - redis:/media/data/redis
            - "${dcUTILS}:/utils"
            - "${APP_UTILS_CONFIG}:/app-utils/conf"
        working_dir: "/data/deploy/current"
        volumes_from:
            - syslog

    syslog:
        container_name: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_syslog"
        hostname: "${dcDEFAULT_APP_NAME}_${CUSTOMER_APP_ENV}_syslog"
        image: "devopscenter/syslog:${dcSTACK_VERSION}"
        env_file:
            - "${GENERATED_ENV_FILE}"
        environment:
            LOG_NAME:
        logging:
            driver: syslog
            options:
                syslog-address: "${SYSLOG_PROTO}://${SYSLOG_SERVER}:${SYSLOG_PORT}"
                syslog-facility: local0
                env: LOG_NAME
                tag: "{{ (.ExtraAttributes nil).LOG_NAME}} {{.Name}}"

# Must include all named volumes in V2 compose file format.
volumes:
    redis:
    pg-db:
